export const ACTION_TYPES = {
  LEAD_CREATED: "LEAD_CREATED",
  LEAD_UPDATED: "LEAD_UPDATED",
  LEAD_DELETED: "LEAD_DELETED",
  STATUS_CHANGED: "STATUS_CHANGED",
  NOTE_ADDED: "NOTE_ADDED",
  FOLLOW_UP_SCHEDULED: "FOLLOW_UP_SCHEDULED",
  FOLLOW_UP_COMPLETED: "FOLLOW_UP_COMPLETED",
  CONVERSATION_CREATED: "CONVERSATION_CREATED",
  CONVERSATION_ASSIGNED: "CONVERSATION_ASSIGNED",
  LEAD_WON: "LEAD_WON",
  ROLE_CHANGED: "ROLE_CHANGED",
  TEAM_MEMBER_REMOVED: "TEAM_MEMBER_REMOVED",
  TEAM_MEMBER_ADDED: "TEAM_MEMBER_ADDED",
  FOLLOW_UP_RESCHEDULED: "FOLLOW_UP_RESCHEDULED",
}

export const NOTIFICATION_TYPES = {
  NEW_LEAD: "NEW_LEAD",
  FOLLOW_UP_DUE: "FOLLOW_UP_DUE",
  NEW_MESSAGE: "NEW_MESSAGE",
  SYSTEM: "SYSTEM",
}

export const LEAD_STATUS = {
  NEW: "NEW",
  CONTACTED: "CONTACTED",
  INTERESTED: "INTERESTED",
  NEGOTIATION: "NEGOTIATION",
  WON: "WON",
  LOST: "LOST",
}

export const LEAD_STATUSES = LEAD_STATUS

export const LEAD_SOURCES = {
  WHATSAPP: "WHATSAPP",
  WEBSITE: "WEBSITE",
  MANUAL: "MANUAL",
  REFERRAL: "REFERRAL",
  OTHER: "OTHER",
}

export const ROLES = {
  ADMIN: "ADMIN",
  USER: "USER",
  MANAGER: "MANAGER",
}
